package com.example.pets_backend.service.fulfillment;

public enum FulfillmentStepKey {

    LOAD_ASSIGNED_ORDER,
    VALIDATE_SERVICE_NODE,
    VALIDATE_FULFILLMENT_STATUS,
    VALIDATE_SERVICE_DATE,
    VALIDATE_LOCATION,
    VALIDATE_SEQUENCE,
    VALIDATE_NOT_DUPLICATE,
    STORE_DIRECT_MEDIA,
    STORE_VIDEO_SOURCE,
    PERSIST_RECORD,
    ADVANCE_ORDER_STATUS,
    SUBMIT_VIDEO_PROCESSING
}
